# Generated by Django 2.2.4 on 2019-08-07 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imgit_app', '0002_auto_20190807_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/')),
                ('gallery_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imgit_app.Gallery')),
            ],
        ),
    ]
