# Generated by Django 2.2.4 on 2019-08-08 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgit_app', '0003_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
