# Generated by Django 2.2.4 on 2019-08-08 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imgit_app', '0006_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user_id',
        ),
    ]
