# Generated by Django 2.2.4 on 2019-08-18 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imgit_app', '0012_auto_20190818_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='author',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
