# Generated by Django 2.2.4 on 2019-08-20 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imgit_app', '0013_auto_20190818_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='gallery_id',
            new_name='gallery',
        ),
    ]
